# Generated by Django 6.0 on 2025-12-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Aplicada'), ('IN_REVIEW', 'En revisión'), ('REJECTED', 'Rechazada'), ('ACCEPTED', 'Aceptada')], default='APPLIED', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_url_override', models.URLField(blank=True)),
            ],
        ),
    ]
