# Generated by Django 6.0 on 2025-12-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modality', models.CharField(choices=[('REMOTE', 'Remoto'), ('HYBRID', 'Híbrido'), ('ONSITE', 'Presencial')], max_length=20)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Tiempo completo'), ('PART_TIME', 'Medio tiempo'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Prácticas')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CLOSED', 'Cerrada')], default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
            ],
        ),
    ]
