# Generated by Django 6.0 on 2025-12-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
